#!/usr/bin/env bash
#
# rec - Terminal Session Recorder (asciinema wrapper)
#
# A wrapper for asciinema that automates recording terminal sessions.
# It generates sanitized, timestamped filenames, records the
# session, and provides an optional upload step.

[[ $1 ]] || {
    echo "usage: ${0##*/} title" >&2
    exit 1
}

title="${*,,}"
title="${title//[^a-z0-9_-]/-}"

while [[ "$title" == *"--"* ]]; do
    title="${title//--/-}"
done

title="${title#?(-)}"
title="${title%?(-)}"

printf -v current_date "%(%%Y%%m%%d%%H%%M)T" -1

file="${title}-${current_date}.cast"
asciinema rec -t "$title" "$file" || exit

read -rp "Upload? [y/N] " yn
[[ $yn =~ ^[Yy]$ ]] || exit

asciinema upload "$file"
